config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
resources :temperatures, path: ''
  root "temperatures#index"
  post "/fetch_temp" => "temperatures#fetch_temp"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/temperature.rb
class Temperature < ApplicationRecord
  validates :warm_bottom_temp, presence: true
  validates :warm_top_temp, presence: true
  validates_numericality_of :warm_top_temp, greater_than: :warm_bottom_temp
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, notice: 'You do not have privileges to set up the temperatures' unless current_user.admin
  end
end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController
  before_action :set_temperature, only: %i[ edit update ]
  before_action :redirect_if_exists, only: %i[  new ]
  before_action :authenticate_admin!, except: [:index, :fetch_temp]

  def fetch_temp
    postcode = params[:postcode]
    pc = UKPostcode.parse(postcode)
      if pc.full_valid?
        url = "https://api.weatherapi.com/v1/forecast.json?key=55b7fdf17805493199a143223212409&q=#{postcode}&days=0"
        begin
          api_response = HTTParty.get(url)
          maxtemp_c = api_response.parsed_response["forecast"]["forecastday"].first["day"]["maxtemp_c"]
          redirect_to temperatures_path(t: maxtemp_c)
        rescue HTTParty::Error, SocketError => e
          redirect_to temperatures_path, notice: 'API not available. Please try again later.'
        end
      else
        redirect_to temperatures_path, notice: 'The postcode is not valid. Please try again.'
      end
  end

  def index
    @temperature = Temperature.last
  end

  def new
    @temperature = Temperature.new
  end
  
  def create
    @temperature = Temperature.new(temperature_params)
    respond_to do |format|
      if @temperature.save
        format.html { redirect_to root_path, notice: 'Temperature was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end
  
  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.html { redirect_to root_path, notice: 'Temperature was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
  def redirect_if_exists
    if Temperature.any? 
      redirect_to edit_temperature_path(Temperature.last), notice: 'Edit the existing temperatures.'
    end
  end

  def set_temperature
    @temperature = Temperature.find(params[:id])
  end

  def temperature_params
    params.require(:temperature).permit(:warm_bottom_temp, :warm_top_temp)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def weather_message(number)
		if number > @temperature.warm_top_temp 
			'Hot' 
		elsif number < @temperature.warm_bottom_temp 
			'Cold' 
		else
			'Warm'
		end
	end

	def admin?
    user_signed_in? && current_user.admin
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Register', new_user_registration_path %></li>
    <% end %>

    <% if flash.any? %>
      <% flash.each do |type, msg| %>
        <div><%= msg %></div>
      <% end %>
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/temperatures/_form.html.erb
<%= form_with(model: temperature) do |form| %>
    <% if temperature.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(temperature.errors.count, "error") %> prohibited this post from being saved:</h2>
  
        <ul>
          <% temperature.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br>
    <div class="temperatures">
      <p>-100°C</p>
      <div>C O L D</div>
      <p><%= form.number_field :warm_bottom_temp, required: true, min: -99, max: 99 %>°C </p>
      <div>W A R M</div>
      <p><%= form.number_field :warm_top_temp, required: true, min: -99, max: 99 %>°C </p>
      <div>H O T</div>
      <p>+ 100°C </p>
      <br><br><br>
      <%= form.submit 'Set the temperatures' %>
    </div>
    </div>
  <% end %>
  

app/views/temperatures/edit.html.erb
<h1>Edit the temperatures</h1>
<%= render "form", temperature: @temperature %>

app/views/temperatures/index.html.erb
<h1>How hot is it today?</h1>

<% if params[:t] %>
  <% temp_today = params[:t].to_i %>
  <h2>It's going to be <%= weather_message(temp_today) %> today.</h2>
<% end %>
  
<% if @temperature.present? %>
  <div>Type your postcode</div><br>
  <%= form_with url: "/fetch_temp", method: :post do |form| %>
  <%= form.text_field :postcode, required: true %>
  <%= form.submit 'Send' %>

  <br><br>
  <% if admin? %>
      <%= link_to "Edit the temperatures", edit_temperature_path(@temperature) %>
  <% end %>
<% end %>

<% else %>
  <div>You need to set up the temparatures first...</div>
  <%= link_to "Set the temperature", new_temperature_path %>
<% end %>

app/views/temperatures/new.html.erb
<h1>Set the temperatures</h1>
<%= render "form", temperature: @temperature %>